# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.

from typing import (
    Any,
    Callable,
    ClassVar,
    Deque,
    FrozenSet,
    Iterable,
    List,
    Mapping,
    Optional,
    Sequence,
    Tuple,
    Union,
)

from html.parser import HTMLParser
from xml.etree import ElementTree

import re

XPathResult = Union[Sequence[str], Sequence[ElementTree.Element]]
XPather = Callable[[ElementTree.Element], XPathResult]
StrTransformer = Callable[[str], Any]
MapTransformer = Callable[[Mapping], Any]
StrExtractor = Callable[[ElementTree.Element], str]
MapExtractor = Callable[[ElementTree.Element], Mapping]
Extractor = Callable[[ElementTree.Element], Any]
Preprocessor = Callable[[ElementTree.Element], None]

__version__: str
_EMPTY: Mapping


class HTMLNormalizer(HTMLParser):
    VOID_ELEMENTS: ClassVar[FrozenSet[str]]
    omit_tags: FrozenSet[str]
    omit_attrs: FrozenSet[str]
    _open_tags: Deque[str]
    _open_omitted_tags: Deque[str]
    def __init__(
        self, *, omit_tags: Iterable[str] = ..., omit_attrs: Iterable[str] = ...
    ) -> None: ...
    def error(self, message: str) -> None: ...

def html_to_xhtml(
    document: str,
    *,
    omit_tags: Iterable[str] = ...,
    omit_attrs: Iterable[str] = ...,
) -> str: ...
def build_tree(
    document: str, *, lxml_html: bool = ...
) -> ElementTree.Element: ...
def get_parent(element: ElementTree.Element) -> ElementTree.Element: ...
def make_xpather(path: str) -> XPather: ...
def make_path(
    path: str,
    sep: Optional[str] = ...,
    transform: Optional[StrTransformer] = ...,
    foreach: Optional[str] = ...,
) -> Extractor: ...
def make_items(
    rules: Sequence[MapExtractor],
    section: Optional[str] = ...,
    transform: Optional[MapTransformer] = ...,
    foreach: Optional[str] = ...,
) -> Extractor: ...
def make_rule(
    key: Union[str, StrExtractor],
    value: Extractor,
    *,
    foreach: Optional[str] = ...,
) -> MapExtractor: ...

class preprocessors:
    @staticmethod
    def remove(path: str) -> Preprocessor: ...
    @staticmethod
    def set_attr(
        path: str, name: Union[str, StrExtractor], value: Union[str, StrExtractor]
    ) -> Preprocessor: ...
    @staticmethod
    def set_text(path: str, text: Union[str, StrExtractor]) -> Preprocessor: ...

class transformers:
    int: Callable[[Any], int]
    float: Callable[[Any], float]
    bool: Callable[[Any], bool]
    len: Callable[[Sequence], int]
    lower: Callable[[str], str]
    upper: Callable[[str], str]
    capitalize: Callable[[str], str]
    lstrip: Callable[[str], str]
    rstrip: Callable[[str], str]
    strip: Callable[[str], str]
    _re_spaces: re.Pattern
    _re_symbols: re.Pattern
    @staticmethod
    def clean(s: str) -> str: ...
    @staticmethod
    def normalize(s: str) -> str: ...

def chain(*functions) -> Callable[[Any], Any]: ...
def load_spec(filepath: str) -> Mapping: ...
def parse_spec(spec: Mapping) -> Tuple[Sequence[Preprocessor], Extractor]: ...
def scrape(
    document: str, spec: Mapping, *, lxml_html: bool = ...
) -> Mapping: ...
def main(argv: Optional[List[str]] = ...) -> None: ...
